server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;
  server_tokens off;

  # trailing slash 경로 통일
  location = /grad {
    return 301 /grad/;
  }

  location = /grad/courses {
    return 301 /grad/courses/;
  }

  location = /grad/status {
    return 301 /grad/status/;
  }

  location = /storage {
    return 301 /storage/;
  }

  location = /profile {
    return 301 /profile/;
  }

  location = /error {
    return 301 /error/;
  }

  location / {
    try_files $uri $uri/ =404;
  }
}
