---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: backend-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBdWTekeNSxbWFsPrnYDju72jOGo9Lx2hGb2BzHgiQWJ68Gb1yzwxet5j6lsbQ6Fa3eZTWTahEqqUftiOSt91i6lQsl4R1vrF8uIUu3IZBLRkWfZy1EKhXHp55MkRHISDax5Mg3B8tPGA1yBEuiHDQUA5TX+a7rYFNzUsyqxOp3wZ3aUnKY+N2FCxv9kty7sm7w6CRU+UeF3sgcxLmpLDjHhLI4gsweM5UqnhNJCVbiZ7ys8FMfpSEB6AP5ZpfeJE7m+SiGe5Nvd0nc8RsNPCVCbxFWFCFZNmUCciJNMiyFhdPDyrnugktfvUHE2Mx02p4eYiAUxQk6G4kNIfHazPgRbURVDtAbbSBvN2rh7XAt56F8pvW/9f32rDVHESquP5py8et7cDeDrejR0R1mn5SoPFgoQsn6XbuZx4NJIX0wvU+fG0z8Nemue7zskgMPnbizxOXhoZoP7RNf8Q1myT0oT12ZItjW8xUw5iXVktp8O0ZFXyY7KFEGMsjhMUXFiyzbYk1J6QPdU3wOuC4UaP7CxixrrO9uGeNmzaTgaNS7QBG2TYEDpzdheiP5mbAz5yDgMnqCb1l/dIjRIoBgUYeTdnY2Fbq3khD+tyrzXFEFJmOX7MFzAFwf5qQeKbaag3hZ3sq2IKo1lFG2oaquDBPKxch8rrbLTvGzE9u0o9yFXo5Q1P1ZEWr63dEv+IBuoQCgX8jCcZ3SvAgQpXCIp/NkhSwOqhhzkQ0o1FRokLl4NQJsGnhuVllJ9DTSjVtPE1kKymy5Kk6YPfgTCINWJi2Kq05GbBzoyDUQk9g666mndup0yYtTDUKQano1CSYeT+Q/J4VwYL7Syde1Hf3LGwQjJS919Vq7KA3oUohFPtNKNgLV+70cHCmLI2dV3/6J1diSofyW47JJ5xvDCfeTXx62V7fGZy6vkKkn7RmEr7Xfr1ixrPO7aG0LlT2BXYISq1HdNZkw/ZdYdP6eLpRG43ER
  template:
    metadata:
      name: ghcr-pull
      namespace: backend-dev
    type: kubernetes.io/dockerconfigjson
