---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: backend-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAnZUoYPRj1PQt6DIziVXekT1/7/QT82nX+n14ccagXBJKGonu8cto1O91i6LEweiZi2XhSNsQi80D03bf7+kPUBZzC0as72xA4w76ZtntHI4CTX/KGAuWEsmLbr2scP/87QohPaPWjlUNGOwBjhldxXPT8xmyIOsU0ahIvpIjlFrS2SVXPZEzvlSS8JfT0NAMt0d5peU8hj6RrEssGtOUqz486LejDdEGG8QZz8RqvJthG/TZR42alDFZkcKtRIv2H+LrztZmYYA3aNJGmIDKvKyW7ZojfYW3Qr9PgbK9YpW3oL8vMHRFIuGmy7oQ+KyZMoidOM1AE5/1oeom53CMk14kw6reutSruz7GuULqjUyFezCUZw8DrqqpNM90XGK36v0/Ws42KIIWPYWKDG5tdP2VLCO2O/pgBC23wlSJX4c5ZtEavsxALMrIjjk6EFc3IcIpvGHUya6sPd8grp+p0Zs/lII0XttpOK+fzYyat2DYuNgnmGatEkPG1ZEuWls3ghkK+I/ogUnqcKuF6AFCqNjf5lEyvLraJ42JU7N+ciD4aXTysbGLIo4GmrtfGEgM1fwFOeZHUx/7LIKwpmerhWjK5eAiGaHOjHhKM+kUyxzoR/tljPjdLLqZb1xZcX2B3k1eV4YxDJ0THCa3kqGUy/r6EaKXUVD1STCT+c9Kku5HNzK7L7Dm+DKxG/QSbm1dP3oMFwIjLHUCWL6tle3bFPIAZHFzQHnAQDCFZe8UZ0GNYVsgjb/UHPp964ofFLvVf7fRbSqKhBMp2/TtDE7De4IhzK80xne5gwYz8zV9Or5XsFA5j5mToHojzrvIzQTVkgu7h2B0n2//53AdtW1wjggr22cWRvl3Y0VnihJPRlgY5YeDIEDGjfXZOp25tIksQ1RCKCacXeKlEvMPVOxqKRlm/yUoeGk/Fesjw8dUQI8tnaKCR4n2wKIzdUnbj4efo6iI3yZW2V5Cjj05fnlsi
  template:
    metadata:
      name: ghcr-pull
      namespace: backend-dev
    type: kubernetes.io/dockerconfigjson
