---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: backend
spec:
  encryptedData:
    .dockerconfigjson: AgAE1I/LJRRdHWdc0yI6HjxVBMuj1kbHzb2GbF+TOGIoxt0PRmNkppSOrGJaFxl6iyVj50vFp7+ZBXAI6X0iFw1luFuaLRWpbrl8dJPPoV3YsL3d+ltARziLQPzUlUR8D5wZAKhNrBKLKu0t4zIpVmxwrFNmrETt9qxa6uRGlG1fZdpynaBLV1M5aYj2LEa0RaAjCzF6pB6EmSiafEQeRfb8+wIm89GYh/WA5sWMUjbMp13nMIClDJCehRNDYgWn4LXs25y8cjdwKYc0e1fOB5gjYCzNCLatOqhNQc02W3RnmlQVD8bics+CHJLyaRfFihZYHvW6uKaIaG7IvKUYC8dKAGJBLs29/K8PLJVu4i65mBFKCZIWODkm34hKqnMcp7i2sAc9ZtQkWdVg/n0C90IPb8N4Y8rTq18eJEaK4DoYNoY4ed/6z+V13D9CdWvHVSPf8uvotqiVR9ocAq1QDQeqT4QAbCMyYo0uw7u2Qw2abaWnBdX6K/EATDvujJTaFjiIsDHG/OMC+Crx3KZ94uTu300qKVbvAnXaZGMYkjTH70EnIgcTEnzW3/e33wwy3E9CdmtCWtUjlJ7G7CeJhq+MN2nXBzhgAipGLBqOLyglBq2BfYbAjIN+5woYYqpj48apHM1HPZcx8KT9R0mkRKjBz0ES+6z82uWPyDN2EnNl3lNI9nCv4InwmakJbSa3rj1SwT7AKvIdgMPu8nuGNTz5OL6Wv8jiBl9HmhD5DmThwB8I7/N1TXLE1toZ4If6bXzC20EetWOp//OxL0swSRBiwiqg2oc2bkOkasHmFm4xutqNJdOb1QGG2UhE9ZzB598bCTmlplvojAiFzZb95UgDf1Hn6eaRY9h+u9aUQA8qk2gLmJVFR9KVxZpyUnQ2X0am9K//rgz5GTsc/QfkN6KM5HeC2dfjQ6VBjMcrC0oBTVhqbPGwzFsb/xqepiNS2P0HJy9hNWj/SYVkVwyDPyKR
  template:
    metadata:
      name: ghcr-pull
      namespace: backend
    type: kubernetes.io/dockerconfigjson
