---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: backend
spec:
  encryptedData:
    .dockerconfigjson: AgBIGxVeBgy7gPp8/hdM513R7dmlbNwlSZ1rT9BNl1KljaWUKfAysrqYa61VuORyN9oOKg2uEm6hrpF7sxxZJP9xucWQTYPhKYZ/mbfvhqO5//Lr4NRor5n2GXc7w0JXLBBH7yo4211b6oRAcysM1lKgj36glNak0VyVbE/zBRdmmHybE6q4sV5eyP+31UcdBdhYBrg+Kjscjpo/Sz6SQu0YPNyjEO3m8oqVC0j9g8MPGe5/y7UST3ohc1bPY6lj7RDkAGUauYkRPe6V9nOu8raJaOBlZFbey88CyTfTK6yjmEys6OVnrbEdb45oizQOQg4NslmroQ6E65l7fLX2tlE2CnTqUuKR1ryw8zOd0v6CsGM7sZZ5lOgy7gU/z6LpdZEDkL//25/trjp2bL/COguz/nDgKgn49OZHYplZRCoH8qGinN104juDvh6juQyVFvrD5ghK0WeWLK+CT3pnAw9xHmRbaGNJ5oYzUijWleNWGLu+YMesAtmRYxd1+pHVFSRl10hDbggt2Uauqz/k20b4RrF+dCQmNTQ2NjEmHrrRwfliBAbKzhdbUqnw/QEnPM77F8p40g+3Vy4yTkO7jReA6l3dBKRkpICXi4zKRtxrP6Wbg1tyvkuiaECJhdCFfBNBYBmtX5NnYbm+0P+hSRVMHSRNzFPW/KciRVPlfhySe9LAYFGb+bq8h8oGtzMrvWA6Lu1pc0sA/DWpimV66Kxo67NbXKd2kW8VQP9B9wne+ruTPOSbSxBnFn+Wm2PmVlmxyfWQuqtaqmWiHBH/8xwU1jsnQMUHJ3wVJ+DKYzwCku75AydBkg+GDGmNfEY1U6grTPONOJUR80Dky2rBAfVVZ4nULad1lniNj4kb9zYUAaVbBXG8FDdms4D5km5x3XdsOCXt+4i7Y8KJaWpXyCNGLKxc6wP67kWNe8ePdRm3ychkieCztjPIHsqYZ2UBwE9IukBmk+/VcF8nUWhe7V1E
  template:
    metadata:
      name: ghcr-pull
      namespace: backend
    type: kubernetes.io/dockerconfigjson
