-- V1__init_tables.sql
-- 테이블 생성 + PK/FK/UNIQUE


-- department : 학부 마스터 테이블
CREATE TABLE department (
    department_id      BIGINT PRIMARY KEY,                  -- 학부 PK
    department_name    VARCHAR(20) NOT NULL,                -- 학부명
    created_at         TIMESTAMP NOT NULL DEFAULT NOW(),    -- 생성 일시

    -- 학부명 중복 허용하지 않음
    CONSTRAINT uq__department__department_name UNIQUE (department_name)
);


-- graduation_template : 졸업요건 템플릿(학부/학번별)
CREATE TABLE graduation_template (
    template_id                     BIGINT PRIMARY KEY,                  -- 템플릿 PK
    department_id                   BIGINT NOT NULL,                     -- 소속 학부 FK
    template_name                   VARCHAR(50) NOT NULL,                -- 템플릿 이름
    applicable_year                 SMALLINT NOT NULL,                   -- 적용 학번/년도
    total_required_credits          SMALLINT NOT NULL,                   -- 총 졸업 필요 학점
    total_culture_credits           SMALLINT NOT NULL,                   -- 총 교양 필요 학점
    total_major_exploration_credits SMALLINT NOT NULL,                   -- 총 전공탐색 필요 학점
    active                          BOOLEAN NOT NULL,                    -- 활성 여부
    created_at                      TIMESTAMP NOT NULL DEFAULT NOW(),    -- 생성 일시

    -- 템플릿은 특정 학부에 속해야함
    CONSTRAINT fk__graduation_template__department_id
        FOREIGN KEY (department_id) REFERENCES department(department_id)
);


-- users : 사용자 계정 테이블
CREATE TABLE users (
    user_id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  -- 사용자 PK(내부 식별자)
    email          VARCHAR(320) NOT NULL,     -- 이메일(로그인 식별자)
    user_name      VARCHAR(50) NOT NULL,      -- 사용자 이름
    department_id  BIGINT NULL,               -- 소속 학부 FK(NULL 허용, 초기 미설정 상태 가능)
    role           VARCHAR(10) NOT NULL,      -- 권한(USER / ADMIN)
    template_id    BIGINT NULL,               -- 적용 졸업요건 템플릿 FK(NULL 허용)
    joined_at      TIMESTAMP NOT NULL DEFAULT NOW(),                     -- 가입 일시
    updated_at     TIMESTAMP NOT NULL DEFAULT NOW(),                     -- 수정 일시

    -- 이메일 중복 허용하지 않음
    CONSTRAINT uq__users__email UNIQUE (email),

    -- 사용자의 소속 학부는 department 테이블에 존재해야함(NULL 허용)
    CONSTRAINT fk__users__department_id
        FOREIGN KEY (department_id) REFERENCES department(department_id),

    -- 사용자의 졸업요건 템플릿은 graduation_template 테이블에 존재해야함(NULL 허용)
    CONSTRAINT fk__users__template_id
        FOREIGN KEY (template_id) REFERENCES graduation_template(template_id)
);


-- major : 전공 마스터 테이블
-- 학부 내 전공 정의
CREATE TABLE major (
    major_id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  -- 전공 PK
    department_id  BIGINT NOT NULL,                                      -- 소속 학부 FK
    major_name     VARCHAR(200) NOT NULL,                                -- 전공명
    created_at     TIMESTAMP NOT NULL DEFAULT NOW(),                     -- 생성 일시

    -- 전공은 반드시 하나의 학부에 속해야함
    CONSTRAINT fk__major__department_id
        FOREIGN KEY (department_id) REFERENCES department(department_id),

    -- 동일 학부 내 전공명 중복 허용하지 않음
    CONSTRAINT uq__major__department_id__major_name
        UNIQUE (department_id, major_name)
);


-- major_credit_rule : 전공 학점 규칙 테이블
-- 전공타입별 전공총 / 전공필수 최소 필요학점 정의
CREATE TABLE major_credit_rule (
    major_credit_rule_id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,   -- 규칙 PK
    major_id                     BIGINT NOT NULL,                                       -- 전공 FK
    major_type                   VARCHAR(8) NOT NULL,                                   -- 전공 타입(심화전공 / 주전공 / 부전공 / 복수전공)
    required_major_total_credits SMALLINT NOT NULL,                                     -- 전공 총 필요 학점
    required_major_core_credits  SMALLINT NOT NULL,                                     -- 전공필수 최소 필요 학점
    created_at                   TIMESTAMP NOT NULL DEFAULT NOW(),                      -- 생성 일시

    -- 학점 규칙은 특정 전공에 속해야함
    CONSTRAINT fk__major_credit_rule__major_id
        FOREIGN KEY (major_id) REFERENCES major(major_id),

    -- 동일 전공에 동일 전공타입 규칙 중복 허용하지 않음
    CONSTRAINT uq__major_credit_rule__major_id__major_type
        UNIQUE (major_id, major_type)
);


-- user_major : 사용자-전공 매핑 테이블
-- 주전공 / 복수전공 / 부전공 / 심화전공 구조 지원
CREATE TABLE user_major (
    user_major_id  BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  -- 사용자-전공 매핑 PK
    user_id        BIGINT NOT NULL,                                      -- 사용자 FK
    major_id       BIGINT NOT NULL,                                      -- 전공 FK
    major_type     VARCHAR(6) NOT NULL,                                  -- 전공 타입(심화전공 / 주전공 / 부전공 / 복수전공)
    created_at     TIMESTAMP NOT NULL DEFAULT NOW(),                     -- 생성 일시

    -- 사용자-전공 매핑은 특정 사용자에 속해야함
    CONSTRAINT fk__user_major__user_id
        FOREIGN KEY (user_id) REFERENCES users(user_id),

    -- 사용자-전공 매핑은 특정 전공에 속해야함
    CONSTRAINT fk__user_major__major_id
        FOREIGN KEY (major_id) REFERENCES major(major_id),

    -- 동일 사용자에 동일 전공 / 전공타입 중복 허용하지 않음
    CONSTRAINT uq__user_major__user_id__major_id__major_type
        UNIQUE (user_id, major_id, major_type)
);


-- culture_credit_rule : 교양 학점 규칙 테이블
CREATE TABLE culture_credit_rule (
    culture_credit_rule_id  BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  -- 교양 규칙 PK
    template_id             BIGINT NOT NULL,                                      -- 템플릿 FK
    rule_category           VARCHAR(10) NOT NULL,                                 -- 규칙 카테고리(교양필수 / 채플 / SEED / 교양선택 / 평생교육)
    required_credits        SMALLINT NOT NULL,                                    -- 필요 학점
    created_at              TIMESTAMP NOT NULL DEFAULT NOW(),                     -- 생성 일시

    -- 교양 규칙은 특정 템플릿에 속해야함
          CONSTRAINT fk__culture_credit_rule__template_id
              FOREIGN KEY (template_id) REFERENCES graduation_template(template_id),

    -- 동일 템플릿에 동일 규칙 카테고리 중복 허용하지 않음
          CONSTRAINT uq__culture_credit_rule__template_id__rule_category
              UNIQUE (template_id, rule_category)
);


-- culture_credit_rule_seed : SEED 상세 영역 규칙 테이블
CREATE TABLE culture_credit_rule_seed (
    culture_credit_rule_seed_id  BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,   -- SEED 규칙 PK
    culture_credit_rule_id       BIGINT NOT NULL,                                       -- 교양 규칙 FK
    seed_name                    VARCHAR(20) NOT NULL,                                  -- SEED 영역명(Science / Economy / Environment / Diversity)
    created_at                   TIMESTAMP NOT NULL DEFAULT NOW(),                      -- 생성 일시

    -- SEED 상세 규칙은 특정 교양 규칙에 속해야함
    CONSTRAINT fk__culture_credit_rule_seed__culture_credit_rule_id
        FOREIGN KEY (culture_credit_rule_id) REFERENCES culture_credit_rule(culture_credit_rule_id),

    -- 동일 교양 규칙에 동일 SEED 영역 중복 허용하지 않음
    CONSTRAINT uq__culture_credit_rule_seed__rule_id__seed_name
        UNIQUE (culture_credit_rule_id, seed_name)
);


-- course_master : 과목 마스터 테이블
-- 과목 검색 / 등록 보조용 카탈로그
CREATE TABLE course_master (
    course_master_id    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  -- 과목 마스터 PK
    course_code         VARCHAR(50) NOT NULL,                                 -- 과목코드(유니크 아님)
    course_name         VARCHAR(300) NOT NULL,                                -- 과목명
    default_credits     SMALLINT NOT NULL,                                    -- 기본 학점
    course_category     VARCHAR(2) NOT NULL,                                  -- 과목 대분류(교양 / 전공)
    course_subcategory  VARCHAR(10) NOT NULL,                                 -- 과목 세부 분류(교양필수 / 채플 / SEED / 교양선택 / 평생교육 / 전공필수 / 전공탐색 / 전공선택)
    seed_area           VARCHAR(20) NULL,                                     -- SEED 영역(NULL 가능)
    opened_year         SMALLINT NULL,                                        -- 개설 연도(NULL 가능, default 과목은 비어있을 수 있음)
    opened_term         VARCHAR(8) NULL,                                      -- 개설 학기(NULL 가능, 1 / SUMMER / 2 / WINTER)
    is_default          BOOLEAN NOT NULL DEFAULT FALSE,                       -- default 과목 여부
    valid_from_year     SMALLINT NULL,                                        -- 적용 시작 연도(NULL 가능)
    valid_to_year       SMALLINT NULL,                                        -- 적용 종료 연도(NULL 가능)
    note                VARCHAR(300) NULL,                                    -- 비고
    created_at          TIMESTAMP NOT NULL DEFAULT NOW()                      -- 생성 일시
);


-- course_master_department_access : 과목-학부 접근 매핑 테이블
-- 전공탐색 / 접근 가능 학부 판단용
CREATE TABLE course_master_department_access (
    course_master_department_access_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  -- 과목-학부 매핑 PK
    course_master_id                   BIGINT NOT NULL,                                      -- 과목 마스터 FK
    department_id                      BIGINT NOT NULL,                                      -- 학부 FK
    created_at                         TIMESTAMP NOT NULL DEFAULT NOW(),                     -- 생성 일시

    -- 과목-학부 매핑은 특정 과목에 속해야함
    CONSTRAINT fk__cm_dept_access__course_master_id
        FOREIGN KEY (course_master_id) REFERENCES course_master(course_master_id),

    -- 과목-학부 매핑은 특정 학부에 속해야함
    CONSTRAINT fk__cm_dept_access__department_id
        FOREIGN KEY (department_id) REFERENCES department(department_id),

    -- 동일 과목에 동일 학부 매핑 중복 허용하지 않음
    CONSTRAINT uq__cm_dept_access__course_master_id__department_id
        UNIQUE (course_master_id, department_id)
);


-- course : 사용자 수강 이력 테이블
-- grad 판정은 이후 course의 snapshot 컬럼만 사용
CREATE TABLE course (
    course_id                BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,   -- 수강 이력 PK
    user_id                  BIGINT NOT NULL,                                       -- 사용자 FK
    course_master_id         BIGINT NULL,                                           -- 과목 마스터 FK(NULL 허용, 수동 입력 과목 가능)
    course_code_snapshot     VARCHAR(50) NOT NULL,                                  -- 판정용 과목코드 스냅샷
    course_name_snapshot     VARCHAR(300) NOT NULL,                                 -- 판정용 과목명 스냅샷
    course_category          VARCHAR(2) NOT NULL,                                   -- 판정용 과목 대분류 스냅샷(교양 / 전공)
    course_subcategory       VARCHAR(10) NOT NULL,                                  -- 판정용 과목 세부 분류 스냅샷
    seed_area                VARCHAR(20) NULL,                                      -- 판정용 SEED 영역 스냅샷(NULL 가능)
    recognition_type         VARCHAR(6) NULL,                                       -- 사용자 입력 전공 인정 타입(NULL이면 교양)
    major_id                 BIGINT NULL,                                           -- 전공 귀속 FK(NULL 가능)
    attributed_department_id BIGINT NULL,                                           -- 전공탐색 귀속 학부 FK(NULL 가능)
    earned_credits           SMALLINT NOT NULL,                                     -- 취득 학점
    grade                    VARCHAR(2) NOT NULL,                                   -- 성적
    taken_year               SMALLINT NOT NULL,                                     -- 수강 연도
    taken_term               VARCHAR(8) NOT NULL,                                   -- 수강 학기(1 / SUMMER / 2 / WINTER)
    retake_course_id         BIGINT NULL,                                           -- 재수강 대상 원본 수강 FK(NULL 가능)
    created_at               TIMESTAMP NOT NULL DEFAULT NOW(),                      -- 생성 일시
    updated_at               TIMESTAMP NOT NULL DEFAULT NOW(),                      -- 수정 일시

    -- 수강 이력은 특정 사용자에 속해야함
    CONSTRAINT fk__course__user_id
        FOREIGN KEY (user_id) REFERENCES users(user_id),

    -- 수강 이력은 특정 과목 마스터에 연결될 수 있음(NULL 허용, 수동 입력 과목은 비어있을 수 있음)
    CONSTRAINT fk__course__course_master_id
        FOREIGN KEY (course_master_id) REFERENCES course_master(course_master_id),

    -- 전공 귀속 전공은 major 테이블에 존재해야함(NULL 허용)
    CONSTRAINT fk__course__major_id
        FOREIGN KEY (major_id) REFERENCES major(major_id),

    -- 전공탐색 귀속 학부는 department 테이블에 존재해야함(NULL 허용)
    CONSTRAINT fk__course__attributed_department_id
        FOREIGN KEY (attributed_department_id) REFERENCES department(department_id),

    -- 재수강 대상 수강 이력은 course 테이블에 존재해야함(NULL 허용)
    CONSTRAINT fk__course__retake_course_id
        FOREIGN KEY (retake_course_id) REFERENCES course(course_id)
            ON DELETE SET NULL
);


-- file_metadata : 파일 메타데이터 테이블
CREATE TABLE file_metadata (
    file_id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  -- 파일 PK
    user_id            BIGINT NOT NULL,                                      -- 사용자 FK
    file_category      VARCHAR(50) NOT NULL,                                 -- 파일 카테고리
    original_filename  VARCHAR(500) NOT NULL,                                -- 원본 파일명
    stored_filename    VARCHAR(200) NOT NULL,                                -- 저장 파일명
    stored_path        TEXT NOT NULL,                                        -- 저장 경로
    content_type       VARCHAR(100) NOT NULL,                                -- MIME 타입
    size_bytes         BIGINT NOT NULL,                                      -- 파일 크기(byte)
    uploaded_at        TIMESTAMP NOT NULL DEFAULT NOW(),                     -- 업로드 일시

    -- 저장 경로 중복 허용하지 않음
    CONSTRAINT uq__file_metadata__stored_path
        UNIQUE (stored_path),

    -- 동일 사용자 기준 동일 원본 파일명 중복 허용하지 않음
    CONSTRAINT uq__file_metadata__user_category_original
        UNIQUE (user_id, original_filename),

    -- 파일은 특정 사용자에 속해야함
    CONSTRAINT fk__file_metadata__user_id
        FOREIGN KEY (user_id) REFERENCES users(user_id)
);


-- user_storage_usage : 사용자별 저장 용량 테이블(1:1)
CREATE TABLE user_storage_usage (
    user_id     BIGINT PRIMARY KEY,                   -- 사용자 PK(users 1:1)
    used_bytes  BIGINT NOT NULL,                      -- 사용량(byte)
    updated_at  TIMESTAMP NOT NULL DEFAULT NOW(),     -- 갱신 일시

    -- 저장 용량 정보는 특정 사용자에 속해야함(1:1)
    CONSTRAINT fk__user_storage_usage__user_id
        FOREIGN KEY (user_id) REFERENCES users(user_id)
);