-- V4__micro_major.sql
-- 마이크로전공 기준 데이터 테이블 + CHECK + INDEX

-- micro_major : 마이크로전공 기준 데이터 테이블
CREATE TABLE micro_major (
    micro_major_id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,   -- 마이크로전공 PK
    micro_major_name       VARCHAR(50) NOT NULL,                                  -- 마이크로전공명
    micro_major_category   VARCHAR(10) NOT NULL,                                  -- 마이크로전공 유형(교양 / 전공 / 융합)
    operating_unit_names   VARCHAR(200) NOT NULL,                                 -- 운영 전공 이름
    required_course_count  SMALLINT NOT NULL,                                     -- 총 필요 과목 수
    required_credits       SMALLINT NOT NULL,                                     -- 총 필요 학점
    valid_from_year        SMALLINT NOT NULL,                                     -- 적용 시작 연도
    valid_from_term        VARCHAR(8) NOT NULL,                                   -- 적용 시작 학기(1 / SUMMER / 2 / WINTER)
    active                 BOOLEAN NOT NULL,                                      -- 활성 여부
    created_at             TIMESTAMP NOT NULL DEFAULT NOW(),                      -- 생성 일시

    -- 마이크로전공명 중복 허용하지 않음
    CONSTRAINT uq__mm__name
        UNIQUE (micro_major_name)
);


-- micro_major_requirement_group : 마이크로전공 요구 그룹 테이블
CREATE TABLE micro_major_requirement_group (
    requirement_group_id   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,   -- 요구 그룹 PK
    micro_major_id         BIGINT NOT NULL,                                       -- 마이크로전공 FK
    group_no               SMALLINT NOT NULL,                                     -- 그룹 번호(응답 표시 순서)
    group_name             VARCHAR(200) NOT NULL,                                 -- 그룹명(전공/학부명)
    required_course_count  SMALLINT NOT NULL,                                     -- 필요 과목 수
    note                   VARCHAR(300) NULL,                                     -- 비고
    created_at             TIMESTAMP NOT NULL DEFAULT NOW(),                      -- 생성 일시

    -- 요구 그룹은 특정 마이크로전공에 속해야함
    CONSTRAINT fk__mmg__mm
        FOREIGN KEY (micro_major_id) REFERENCES micro_major(micro_major_id),

    -- 동일 마이크로전공에 동일 그룹 번호 중복 허용하지 않음
    CONSTRAINT uq__mmg__mm__gno
        UNIQUE (micro_major_id, group_no)
);


-- micro_major_requirement_course : 요구 그룹별 인정 과목 테이블
CREATE TABLE micro_major_requirement_course (
    requirement_course_id     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,   -- 인정 과목 행 PK
    requirement_group_id      BIGINT NOT NULL,                                       -- 요구 그룹 FK
    recognized_course_code    VARCHAR(50) NULL,                                      -- 인정 과목 코드(판정 기준)
    recognized_course_name    VARCHAR(200) NOT NULL,                                 -- 인정 과목명(표시 / 검증용)
    requirement_slot_key      VARCHAR(100) NOT NULL,                                 -- 동일과목 / 대체인정 묶음 키
    display_order             SMALLINT NOT NULL,                                     -- 그룹 내 슬롯 표시 순서
    valid_from_year_override  SMALLINT NULL,                                         -- 과목별 적용 시작 연도 예외값
    valid_from_term_override  VARCHAR(8) NULL,                                       -- 과목별 적용 시작 학기 예외값
    note                      VARCHAR(300) NULL,                                     -- 비고
    created_at                TIMESTAMP NOT NULL DEFAULT NOW(),                      -- 생성 일시

    -- 인정 과목은 특정 요구 그룹에 속해야함
    CONSTRAINT fk__mmc__group
        FOREIGN KEY (requirement_group_id) REFERENCES micro_major_requirement_group(requirement_group_id),

    -- 동일 요구 그룹에 동일 과목코드 중복 허용하지 않음
    CONSTRAINT uq__mmc__group__code
        UNIQUE (requirement_group_id, recognized_course_code)
);


-- micro_major_eligibility : 마이크로전공 이수 가능 자격 조건 테이블
CREATE TABLE micro_major_eligibility (
    micro_major_eligibility_id  BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,   -- 자격 조건 행 PK
    micro_major_id              BIGINT NOT NULL,                                        -- 마이크로전공 FK
    eligibility_group_no        SMALLINT NOT NULL,                                      -- 자격 조건 그룹 번호(그룹 간 AND, 그룹 내 OR)
    eligibility_type            VARCHAR(10) NOT NULL,                                   -- 자격 조건 유형(DEPARTMENT / MAJOR)
    department_id               BIGINT NULL,                                            -- 학부 조건 FK
    major_id                    BIGINT NULL,                                            -- 전공 조건 FK
    note                        VARCHAR(300) NULL,                                      -- 비고
    created_at                  TIMESTAMP NOT NULL DEFAULT NOW(),                       -- 생성 일시

    -- 자격 조건은 특정 마이크로전공에 속해야함
    CONSTRAINT fk__mme__mm
        FOREIGN KEY (micro_major_id) REFERENCES micro_major(micro_major_id),

    -- 자격 조건의 학부는 department 테이블에 존재해야함(NULL 허용)
    CONSTRAINT fk__mme__dept
        FOREIGN KEY (department_id) REFERENCES department(department_id),

    -- 자격 조건의 전공은 major 테이블에 존재해야함(NULL 허용)
    CONSTRAINT fk__mme__major
        FOREIGN KEY (major_id) REFERENCES major(major_id)
);


-- CHECK 제약

-- micro_major
ALTER TABLE micro_major
    ADD CONSTRAINT chk__mm__cat
        CHECK (micro_major_category IN ('교양', '전공', '융합'));

ALTER TABLE micro_major
    ADD CONSTRAINT chk__mm__term
        CHECK (valid_from_term IN ('1', 'SUMMER', '2', 'WINTER'));

ALTER TABLE micro_major
    ADD CONSTRAINT chk__mm__req_course
        CHECK (required_course_count > 0);

ALTER TABLE micro_major
    ADD CONSTRAINT chk__mm__req_credit
        CHECK (required_credits > 0);


-- micro_major_requirement_group
ALTER TABLE micro_major_requirement_group
    ADD CONSTRAINT chk__mmg__gno
        CHECK (group_no > 0);

ALTER TABLE micro_major_requirement_group
    ADD CONSTRAINT chk__mmg__req_course
        CHECK (required_course_count > 0);


-- micro_major_requirement_course
ALTER TABLE micro_major_requirement_course
    ADD CONSTRAINT chk__mmc__ord
        CHECK (display_order > 0);

ALTER TABLE micro_major_requirement_course
    ADD CONSTRAINT chk__mmc__term_ovr
        CHECK (valid_from_term_override IS NULL OR valid_from_term_override IN ('1', 'SUMMER', '2', 'WINTER'));

-- 과목별 적용 시작 연도/학기 예외값은 둘 다 없거나 둘 다 있어야 함
ALTER TABLE micro_major_requirement_course
    ADD CONSTRAINT chk__mmc__ovr_pair
        CHECK (
            (valid_from_year_override IS NULL AND valid_from_term_override IS NULL)
                OR
            (valid_from_year_override IS NOT NULL AND valid_from_term_override IS NOT NULL)
            );


-- micro_major_eligibility
ALTER TABLE micro_major_eligibility
    ADD CONSTRAINT chk__mme__type
        CHECK (eligibility_type IN ('DEPARTMENT', 'MAJOR'));

ALTER TABLE micro_major_eligibility
    ADD CONSTRAINT chk__mme__gno
        CHECK (eligibility_group_no > 0);

-- DEPARTMENT : department_id NOT NULL, major_id NULL
-- MAJOR      : department_id NULL, major_id NOT NULL
ALTER TABLE micro_major_eligibility
    ADD CONSTRAINT chk__mme__pair
        CHECK (
            (eligibility_type = 'DEPARTMENT'
                AND department_id IS NOT NULL
                AND major_id IS NULL)
                OR
            (eligibility_type = 'MAJOR'
                AND department_id IS NULL
                AND major_id IS NOT NULL)
            );


-- INDEX

-- micro_major
CREATE INDEX IF NOT EXISTS idx__mm__active
    ON micro_major(active);

CREATE INDEX IF NOT EXISTS idx__mm__cat
    ON micro_major(micro_major_category);


-- micro_major_requirement_group
CREATE INDEX IF NOT EXISTS idx__mmg__mm
    ON micro_major_requirement_group(micro_major_id);


-- micro_major_requirement_course
CREATE INDEX IF NOT EXISTS idx__mmc__group
    ON micro_major_requirement_course(requirement_group_id);

CREATE INDEX IF NOT EXISTS idx__mmc__code
    ON micro_major_requirement_course(recognized_course_code);

CREATE INDEX IF NOT EXISTS idx__mmc__slot
    ON micro_major_requirement_course(requirement_slot_key);


-- micro_major_eligibility
CREATE INDEX IF NOT EXISTS idx__mme__mm
    ON micro_major_eligibility(micro_major_id);

CREATE INDEX IF NOT EXISTS idx__mme__dept
    ON micro_major_eligibility(department_id);

CREATE INDEX IF NOT EXISTS idx__mme__major
    ON micro_major_eligibility(major_id);

CREATE INDEX IF NOT EXISTS idx__mme__gno
    ON micro_major_eligibility(eligibility_group_no);

-- 동일 마이크로전공 + 동일 자격 그룹 안에서 같은 학부 조건 중복 허용하지 않음
CREATE UNIQUE INDEX uq__mme__mm__gno__dept
    ON micro_major_eligibility(micro_major_id, eligibility_group_no, department_id)
    WHERE eligibility_type = 'DEPARTMENT';

-- 동일 마이크로전공 + 동일 자격 그룹 안에서 같은 전공 조건 중복 허용하지 않음
CREATE UNIQUE INDEX uq__mme__mm__gno__major
    ON micro_major_eligibility(micro_major_id, eligibility_group_no, major_id)
    WHERE eligibility_type = 'MAJOR';