// Courses 페이지 검색/수강 목록에서 재사용하는 연도 옵션
// Courses 페이지 mock 옵션과 더미 데이터를 모아둔 모듈.

// 공통 옵션 데이터
export const COURSE_YEAR_OPTIONS = ["2026", "2025", "2024", "2023", "2022", "2021"];

// 학기 선택 드롭다운 공통 옵션
export const COURSE_TERM_OPTIONS = [
  { value: "1", label: "1" },
  { value: "SUMMER", label: "SUMMER" },
  { value: "2", label: "2" },
  { value: "WINTER", label: "WINTER" },
];

// 과목 검색/수정 폼에서 공통으로 사용하는 세부 구분 옵션
export const COURSE_SUBCATEGORY_OPTIONS = [
  { value: "교양필수", label: "교양필수" },
  { value: "채플", label: "채플" },
  { value: "SEED", label: "SEED" },
  { value: "교양선택", label: "교양선택" },
  { value: "평생교육", label: "평생교육" },
  { value: "전공필수", label: "전공필수" },
  { value: "전공탐색", label: "전공탐색" },
  { value: "전공선택", label: "전공선택" },
];

// Edit Course 팝업 성적 선택 옵션
export const COURSE_GRADE_OPTIONS = [
  { value: "A+", label: "A+" },
  { value: "A0", label: "A0" },
  { value: "B+", label: "B+" },
  { value: "B0", label: "B0" },
  { value: "C+", label: "C+" },
  { value: "C0", label: "C0" },
  { value: "D+", label: "D+" },
  { value: "D0", label: "D0" },
  { value: "F", label: "F" },
  { value: "P", label: "P" },
  { value: "NP", label: "NP" },
];

// 전공 선택 팝업/수정 팝업에서 보여줄 사용자 전공 더미 데이터
export const COURSE_MAJOR_OPTIONS = [
  { value: "computer-science", label: "컴퓨터공학" },
  { value: "business-administration", label: "경영학" },
  { value: "media-contents", label: "미디어콘텐츠" },
];

// Edit Course 팝업의 귀속 학과 선택 더미 데이터
export const COURSE_DEPARTMENT_OPTIONS = [
  { value: "sw-convergence", label: "소프트웨어융합대학" },
  { value: "business-school", label: "경영대학" },
  { value: "humanities-college", label: "인문대학" },
];

// Search Courses UI 확인용 더미 검색 결과 데이터
// 검색용 카탈로그 더미 데이터
export const SEARCH_COURSE_DUMMY_DATA = [
  {
    code: "CSE2103",
    name: "Data Structures",
    credits: 3,
    category: "Major",
    subcategory: "전공필수",
    year: "2026",
    term: "1",
    majorSelectionMode: "multiple",
  },
  {
    code: "BUS3002",
    name: "Consumer Behavior",
    credits: 3,
    category: "Major",
    subcategory: "전공선택",
    year: "2026",
    term: "1",
    majorSelectionMode: "single",
  },
  {
    code: "MJR1001",
    name: "Major Foundation Studio",
    credits: 2,
    category: "Major",
    subcategory: "전공필수",
    year: "2026",
    term: "SUMMER",
    majorSelectionMode: "empty",
  },
  {
    code: "CSE3301",
    name: "Database Systems",
    credits: 3,
    category: "Major",
    subcategory: "전공선택",
    year: "2026",
    term: "2",
    majorSelectionMode: "multiple",
  },
  {
    code: "HUM1101",
    name: "Academic Writing",
    credits: 2,
    category: "General Education",
    subcategory: "교양필수",
    year: "2026",
    term: "1",
    majorSelectionMode: "none",
  },
  {
    code: "CHP1001",
    name: "Chapel I",
    credits: 0,
    category: "Chapel",
    subcategory: "채플",
    year: "2026",
    term: "1",
    majorSelectionMode: "none",
  },
  {
    code: "SEE2001",
    name: "Career Design Lab",
    credits: 1,
    category: "General Education",
    subcategory: "SEED",
    year: "2025",
    term: "WINTER",
    majorSelectionMode: "none",
  },
  {
    code: "HIS2102",
    name: "Korean History and Identity",
    credits: 3,
    category: "General Education",
    subcategory: "교양선택",
    year: "2025",
    term: "2",
    majorSelectionMode: "none",
  },
  {
    code: "EDU3005",
    name: "Lifelong Learning Seminar",
    credits: 2,
    category: "Lifelong Education",
    subcategory: "평생교육",
    year: "2025",
    term: "SUMMER",
    majorSelectionMode: "none",
  },
  {
    code: "CSE1205",
    name: "AI Computing Basics",
    credits: 3,
    category: "Major",
    subcategory: "전공탐색",
    year: "2025",
    term: "1",
    majorSelectionMode: "none",
  },
  {
    code: "MKT3101",
    name: "Digital Branding",
    credits: 3,
    category: "Major",
    subcategory: "전공선택",
    year: "2024",
    term: "WINTER",
    majorSelectionMode: "multiple",
  },
  {
    code: "ART2203",
    name: "Creative Thinking Workshop",
    credits: 2,
    category: "General Education",
    subcategory: "교양선택",
    year: "2024",
    term: "2",
    majorSelectionMode: "none",
  },
  {
    code: "CSE4407",
    name: "Operating Systems",
    credits: 3,
    category: "Major",
    subcategory: "전공필수",
    year: "2024",
    term: "1",
    majorSelectionMode: "multiple",
  },
  {
    code: "PHY1002",
    name: "Science in Everyday Life",
    credits: 3,
    category: "General Education",
    subcategory: "교양필수",
    year: "2023",
    term: "2",
    majorSelectionMode: "none",
  },
];

// Taken Courses UI 확인용 더미 수강 과목 데이터
// 수강 이력 더미 데이터
export const TAKEN_COURSE_DUMMY_DATA = [
  {
    courseId: "taken-001",
    code: "CSE4010",
    name: "Capstone Design Project",
    earnedCredits: 3,
    takenYear: "2025",
    takenTerm: "WINTER",
    courseSubcategory: "전공선택",
    isRetake: false,
    grade: "A+",
    attributedMajorId: "computer-science",
    attributedDepartmentId: "sw-convergence",
    retakeCourseId: "",
  },
  {
    courseId: "taken-002",
    code: "BUS3204",
    name: "Service Operations",
    earnedCredits: 3,
    takenYear: "2025",
    takenTerm: "2",
    courseSubcategory: "전공선택",
    isRetake: false,
    grade: "A0",
    attributedMajorId: "business-administration",
    attributedDepartmentId: "business-school",
    retakeCourseId: "",
  },
  {
    courseId: "taken-003",
    code: "CHP1002",
    name: "Chapel II",
    earnedCredits: 0,
    takenYear: "2025",
    takenTerm: "2",
    courseSubcategory: "채플",
    isRetake: false,
    grade: "P",
    attributedMajorId: "",
    attributedDepartmentId: "",
    retakeCourseId: "",
  },
  {
    courseId: "taken-004",
    code: "HUM2101",
    name: "Technical Communication",
    earnedCredits: 2,
    takenYear: "2025",
    takenTerm: "SUMMER",
    courseSubcategory: "교양선택",
    isRetake: false,
    grade: "A0",
    attributedMajorId: "",
    attributedDepartmentId: "humanities-college",
    retakeCourseId: "",
  },
  {
    courseId: "taken-005",
    code: "CSE2103",
    name: "Data Structures",
    earnedCredits: 3,
    takenYear: "2025",
    takenTerm: "1",
    courseSubcategory: "전공필수",
    isRetake: true,
    grade: "A+",
    attributedMajorId: "computer-science",
    attributedDepartmentId: "sw-convergence",
    retakeCourseId: "taken-011",
  },
  {
    courseId: "taken-006",
    code: "ECO2001",
    name: "Principles of Economics",
    earnedCredits: 3,
    takenYear: "2025",
    takenTerm: "1",
    courseSubcategory: "교양선택",
    isRetake: false,
    grade: "B0",
    attributedMajorId: "",
    attributedDepartmentId: "business-school",
    retakeCourseId: "",
  },
  {
    courseId: "taken-007",
    code: "CSE3301",
    name: "Database Systems",
    earnedCredits: 3,
    takenYear: "2024",
    takenTerm: "WINTER",
    courseSubcategory: "전공선택",
    isRetake: false,
    grade: "A0",
    attributedMajorId: "computer-science",
    attributedDepartmentId: "sw-convergence",
    retakeCourseId: "",
  },
  {
    courseId: "taken-008",
    code: "SEE2001",
    name: "Career Design Lab",
    earnedCredits: 1,
    takenYear: "2024",
    takenTerm: "2",
    courseSubcategory: "SEED",
    isRetake: false,
    grade: "P",
    attributedMajorId: "",
    attributedDepartmentId: "",
    retakeCourseId: "",
  },
  {
    courseId: "taken-009",
    code: "MKT3101",
    name: "Digital Branding",
    earnedCredits: 3,
    takenYear: "2024",
    takenTerm: "2",
    courseSubcategory: "전공선택",
    isRetake: false,
    grade: "B+",
    attributedMajorId: "business-administration",
    attributedDepartmentId: "business-school",
    retakeCourseId: "",
  },
  {
    courseId: "taken-010",
    code: "MAT1202",
    name: "Discrete Mathematics",
    earnedCredits: 3,
    takenYear: "2024",
    takenTerm: "1",
    courseSubcategory: "전공필수",
    isRetake: false,
    grade: "B0",
    attributedMajorId: "computer-science",
    attributedDepartmentId: "sw-convergence",
    retakeCourseId: "",
  },
  {
    courseId: "taken-011",
    code: "CSE2103",
    name: "Data Structures",
    earnedCredits: 3,
    takenYear: "2023",
    takenTerm: "1",
    courseSubcategory: "전공필수",
    isRetake: false,
    grade: "C+",
    attributedMajorId: "computer-science",
    attributedDepartmentId: "sw-convergence",
    retakeCourseId: "",
  },
  {
    courseId: "taken-012",
    code: "HUM1101",
    name: "Academic Writing",
    earnedCredits: 2,
    takenYear: "2023",
    takenTerm: "SUMMER",
    courseSubcategory: "교양필수",
    isRetake: false,
    grade: "A0",
    attributedMajorId: "",
    attributedDepartmentId: "humanities-college",
    retakeCourseId: "",
  },
  {
    courseId: "taken-013",
    code: "CHM1005",
    name: "Modern Science Literacy",
    earnedCredits: 3,
    takenYear: "2023",
    takenTerm: "2",
    courseSubcategory: "교양필수",
    isRetake: false,
    grade: "B+",
    attributedMajorId: "",
    attributedDepartmentId: "humanities-college",
    retakeCourseId: "",
  },
  {
    courseId: "taken-014",
    code: "BUS2007",
    name: "Accounting Basics",
    earnedCredits: 3,
    takenYear: "2022",
    takenTerm: "WINTER",
    courseSubcategory: "전공탐색",
    isRetake: false,
    grade: "B0",
    attributedMajorId: "business-administration",
    attributedDepartmentId: "business-school",
    retakeCourseId: "",
  },
  {
    courseId: "taken-015",
    code: "BUS3204",
    name: "Service Operations",
    earnedCredits: 3,
    takenYear: "2023",
    takenTerm: "2",
    courseSubcategory: "전공선택",
    isRetake: false,
    grade: "B+",
    attributedMajorId: "business-administration",
    attributedDepartmentId: "business-school",
    retakeCourseId: "",
  },
  {
    courseId: "taken-016",
    code: "CSE3301",
    name: "Database Systems",
    earnedCredits: 3,
    takenYear: "2023",
    takenTerm: "SUMMER",
    courseSubcategory: "전공선택",
    isRetake: false,
    grade: "C0",
    attributedMajorId: "computer-science",
    attributedDepartmentId: "sw-convergence",
    retakeCourseId: "",
  },
  {
    courseId: "taken-017",
    code: "MKT3101",
    name: "Digital Branding",
    earnedCredits: 3,
    takenYear: "2022",
    takenTerm: "1",
    courseSubcategory: "전공선택",
    isRetake: false,
    grade: "B0",
    attributedMajorId: "business-administration",
    attributedDepartmentId: "business-school",
    retakeCourseId: "",
  },
];
