spring:
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "https://api.khuoo.synology.me/login/oauth2/code/google"

management:
  endpoint:
    health:
      show-details: never

app:
  dev-token:
    enabled: false
  storage:
    root: /mnt/nas/mgm-files
  jwt:
    secret: "${JWT_SECRET}"
    exp-seconds: 604800  # 7일
  auth:
    cookie-domain: .khuoo.synology.me
    redirect-url: "https://api.khuoo.synology.me/swagger-ui/index.html"
  swagger:
    server-url: https://api.khuoo.synology.me