spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"

app:
  dev-token:
    enabled: true
  storage:
    root: /tmp/gradmanager_local_storage
  jwt:
    secret: "kK0PP8dHYQ30llX7KnFS58DvIcmIN4kVSMxsJdD32gY="
    exp-seconds: 604800  # 7일
  auth:
    cookie-secure: false
    cookie-domain: ""
    redirect-url: http://localhost:5173/grad/
    allowed-origins:
      - http://localhost:5173
      - http://127.0.0.1:5173
  swagger:
    server-url: http://localhost:8080

springdoc:
  swagger-ui:
    persistAuthorization: false
