apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  strategy:
    $patch: replace
    type: Recreate
  template:
    metadata:
      annotations:
        gitops-test: "frontend-dev-overlay"
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: frontend
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
