apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend-dev

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml

images:
- name: ghcr.io/khuoo4603/my-graduation-manager-frontend
  newName: ghcr.io/khuoo4603/my-graduation-manager-frontend
  newTag: sha-4c0de06
